apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: linstor
spec:
  version: {{ .TagName }}
  homepage: https://github.com/piraeusdatastore/kubectl-linstor
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/piraeusdatastore/kubectl-linstor/releases/download/{{ .TagName }}/kubectl-linstor-{{ .TagName }}-darwin-amd64.tar.gz" .TagName }}
      files:
        - from: ./kubectl-linstor
          to: .
        - from: ./LICENSE
          to: .
      bin: kubectl-linstor
    - selector:
      matchLabels:
        os: darwin
        arch: arm64
      {{addURIAndSha "https://github.com/piraeusdatastore/kubectl-linstor/releases/download/{{ .TagName }}/kubectl-linstor-{{ .TagName }}-darwin-arm64.tar.gz" .TagName }}
      files:
        - from: ./kubectl-linstor
          to: .
        - from: ./LICENSE
          to: .
      bin: kubectl-linstor
      - selector:
          matchLabels:
            os: linux
            arch: amd64
        {{addURIAndSha "https://github.com/piraeusdatastore/kubectl-linstor/releases/download/{{ .TagName }}/kubectl-linstor-{{ .TagName }}-linux-amd64.tar.gz" .TagName }}
        files:
          - from: ./kubectl-linstor
            to: .
          - from: ./LICENSE
            to: .
        bin: kubectl-linstor
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      {{addURIAndSha "https://github.com/piraeusdatastore/kubectl-linstor/releases/download/{{ .TagName }}/kubectl-linstor-{{ .TagName }}-linux-arm64.tar.gz" .TagName }}
      files:
        - from: ./kubectl-linstor
          to: .
        - from: ./LICENSE
          to: .
      bin: kubectl-linstor
    - selector:
        matchLabels:
          os: linux
          arch: s390x
      {{addURIAndSha "https://github.com/piraeusdatastore/kubectl-linstor/releases/download/{{ .TagName }}/kubectl-linstor-{{ .TagName }}-linux-s390x.tar.gz" .TagName }}
      files:
        - from: ./kubectl-linstor
          to: .
        - from: ./LICENSE
          to: .
      bin: kubectl-linstor
  shortDescription: View and manage LINSTOR storage resources
  description: |
    Usage:
      kubectl linstor ...
      Executes control commands for the LINSTOR storage system directly via kubectl.
      Read more documentation at: https://github.com/piraeusdatastore/kubectl-linstor
