on:
  release:
    types: [created]

jobs:
  release:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, s390x, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.14
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: ${{ matrix.goarch }}
          goversion: https://golang.org/dl/go1.15.8.linux-amd64.tar.gz
          extra_files: LICENSE README.md
          sha256sum: TRUE
